# Generated by Django 4.1.13 on 2024-01-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeVideo',
        ),
    ]
